# NB: don't set `language: haskell` here
language: c
dist: xenial

git:
  submodules: false

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.ghc-install

before_cache:
  - rm -fv $CABALHOME/packages/hackage.haskell.org/build-reports.log
  - rm -fv $CABALHOME/packages/hackage.haskell.org/00-index.*
  - rm -fv $CABALHOME/packages/hackage.haskell.org/*.json
  - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.cache
  - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar
  - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar.idx
  - rm -rfv $CABALHOME/packages/head.hackage

notifications:
  email:
    - erkokl@gmail.com
  on_success: always
  on_failure: always

matrix:
  include:
    - compiler: "ghc-8.10.1"
      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-3.2,ghc-8.10.1], sources: [hvr-ghc]}}

before_install:
  - HC=/opt/ghc/bin/${CC}
  - HCPKG=${HC/ghc/ghc-pkg}
  - unset CC
  - CABAL=/opt/ghc/bin/cabal
  - CABALHOME=$HOME/.cabal
  - export PATH="$CABALHOME/bin:$PATH"
  - ROOTDIR=$(pwd)
  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
  - echo $HCNUMVER

install:
  - ${CABAL} --version
  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
# - TEST=--enable-tests
  - TEST=
# - BENCH=--enable-benchmarks
  - BENCH=
  - GHCHEAD=${GHCHEAD-false}
  - travis_retry ${CABAL} update -v
  - sed -i.bak 's/^jobs:/-- jobs:/' $CABALHOME/config
  - rm -fv cabal.project cabal.project.local
  - grep -Ev -- '^\s*--' $CABALHOME/config | grep -Ev '^\s*$'
  - rm -f cabal.project
  - touch cabal.project
  - "printf 'packages: \".\"\\n' >> cabal.project"
  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
  - touch cabal.project.local
  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | grep -vE -- '^(sbv)$' | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
  - cat cabal.project || true
  - cat cabal.project.local || true
  - if [ -f "./configure.ac" ]; then (cd "." && autoreconf -i); fi
  - rm -f cabal.project.freeze
  - ${CABAL} new-freeze -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dry
  - "cat \"cabal.project.freeze\" | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
  - rm  "cabal.project.freeze"
  - ${CABAL} new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
  - rm -rf .ghc.environment.* "."/dist
  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)

script:
  - ${CABAL} new-install -w ${HC} ${TEST} ${BENCH} all --lib
  - ${CABAL} check
